service:
  name: health-analyzer

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8010
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      convertEmptyValues: true
      migrate: true
  dotenv:
    path: ./.env
    include:
      - LINE_BOT_CHANNEL_ACCESSTOKEN
      - LINE_BOT_CHANNEL_ID
      - LINE_BOT_CHANNEL_SECRET
      - LINE_AUTH_CHANNEL_ID
      - LINE_AUTH_CHANNEL_SECRET
      - LINE_NOTIFY_CLIENT_ID
      - LINE_NOTIFY_CLIENT_SECRET

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: src/app.handler
    memorySize: 128
    timeout: 900
    events:
      - http: ANY /
      - http: ANY /{proxy+}

#  schedule_regist:
#    handler: src/schedule.regist
#    memorySize: 128
#    timeout: 900
#    events:
#      - http:
#          method: post
#          path: schedule/regist
#          cors: true

#  schedule_update:
#    handler: src/schedule.update
#    memorySize: 128
#    timeout: 900
#    events:
#      - http:
#          method: post
#          path: schedule/update
#          cors: true

#  schedule_delete:
#    handler: src/schedule.remove
#    memorySize: 128
#    timeout: 900
#    events:
#      - http:
#          method: post
#          path: schedule/remove
#          cors: true

#  notify:
#    handler: src/notify.routine
#    memorySize: 128
#    timeout: 900
#    events:
#      - schedule:
#          rate: rate(1 minutes)
#          enabled: true
#          input:
#            key1: value1
#            key2: value2
#            stageParams:
#              stage: dev